version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      # PGDATA: /data/postgres
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - app-network
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    command: redis-server --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./docker-volumes/cache:/data
    networks:
      - app-network

  # redis-commander:
  #   container_name: redis-commander-container
  #   image: ghcr.io/joeferner/redis-commander:latest
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
